version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.99.100:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'kafka'
      MYSQL_USER: 'kafkauser'
      MYSQL_PASSWORD: 'kafkapassword'
      MYSQL_ROOT_PASSWORD: 'kafkapassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - data:/var/lib/mysql
volumes:
  data: