spring:
  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
    # Kafka cluster or Docker IP
    bootstrap-servers: 192.168.99.100:9092

topic:
  topic-name: advice-topic