spring:
  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: 192.168.99.100:9092
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: mysql
    url: jdbc:mysql://192.168.99.100:3306/kafka
    username: kafkauser
    password: kafkapassword
    driverClassName: com.mysql.cj.jdbc.Driver

topic:
  topic-name: advice-topic
  messages-per-request: 10
  
phonecall:
  rate-per-second: 0.1
  rate-per-mb: 0.05